### ISSUE TITLE
Code for htm.SparseWeights2d and htm.KWinners2d

### ISSUE THREAD

**Issue by cohen-rachel** [jammer345/SL-CycleGAN-Blind-Motion-Deblurring-in-Cycles-using-Sparse-Learning#3]
The code for htm.SparseWeights2d and htm.KWinners2d seem to be missing, as they appear to be custom modules. 

I did find this repo https://github.com/water-vapor/how-can-we-be-so-dense-pytorch/tree/master which your paper cites several times. Can I use the code in this repo for those functions?

**Comment by LiYunJamesPhD** [comment]
Hi,

Thanks for being interested in our work. Yes, you can use that repo for htm.SparseWeights2d and htm.KWinners2d.
